version: '3.4'
name: ivnav-store


services:

  # Identity
  ivnav.store.identity:
    container_name: ivnav.store.identity
    image: ${DOCKER_REGISTRY-}ivnavstore.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DbConnection=${DB_CONNECTION_STRING_IDENTITY}
    build:
      context: .
      dockerfile: IvNav.Store.Identity.Web/Dockerfile

  ivnav.store.identity-dapr:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "-app-id", "ivnav-identity",
      "-app-port", "443",
      "-app-ssl", "true"
    ]
    depends_on:
      - ivnav.store.identity
    network_mode: "service:ivnav.store.identity"


  # Mail
  ivnav.store.mail:
    container_name: ivnav.store.mail
    image: ${DOCKER_REGISTRY-}ivnavstore-mail
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    build:
      context: .
      dockerfile: IvNav.Store.Mail.Web/Dockerfile

  ivnav.store.mail-dapr:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "-app-id", "ivnav-store-mail",
      "-app-port", "443",
      "-app-ssl", "true"
    ]
    depends_on:
      - ivnav.store.mail
    network_mode: "service:ivnav.store.mail"


  # Product
  ivnav.store.product:
    container_name: ivnav.store.product
    image: ${DOCKER_REGISTRY-}ivnavstore-product
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DbConnection=${DB_CONNECTION_STRING_PRODUCT}
    build:
      context: .
      dockerfile: IvNav.Store.Product.Web/Dockerfile

  ivnav.store.product-dapr:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "-app-id", "ivnav-store-product",
      "-app-port", "443",
      "-app-ssl", "true"
    ]
    depends_on:
      - ivnav.store.product
    network_mode: "service:ivnav.store.product"
