version: '3.4'
name: ivnav-store


services:
  ivnav.store.webapi:
    container_name: ivnav.store.webapi
    image: ${DOCKER_REGISTRY-}ivnavstore.webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DbConnection=${DB_CONNECTION_STRING}
    build:
      context: .
      dockerfile: IvNav.Store.Web/Dockerfile

  ivnav.store.webapi-dapr:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "-app-id", "ivnav-store",
      "-app-port", "443",
      "-app-ssl", "true"
    ]
    depends_on:
      - ivnav.store.webapi
    network_mode: "service:ivnav.store.webapi"

  ivnav.store.mail:
    container_name: ivnav.store.mail
    image: ${DOCKER_REGISTRY-}ivnavstore-mail
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    build:
      context: .
      dockerfile: IvNav.Store.Mail.Web/Dockerfile

  ivnav.store.mail-dapr:
    image: "daprio/daprd:latest"
    command: [
      "./daprd",
      "-app-id", "ivnav-store-mail",
      "-app-port", "443",
      "-app-ssl", "true"
    ]
    depends_on:
      - ivnav.store.mail
    network_mode: "service:ivnav.store.mail"
